# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUI-tutorials' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUI-tutorials
  pod 'ExytePopupView'
  pod 'Alamofire', '~> 5.2'
  pod 'URLImage'

end
